name: Status Checks

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  rubocop:
    name: Rubocop
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
          bundler-cache: true
      - run: bundle exec rubocop

  test:
    name: Tests
    runs-on: [self-hosted, linux]

    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7]

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake test
