name: Status Checks

on:
  push:
    paths-ignore:
      - '**.md'

jobs:

  container-job:
    runs-on: [self-hosted, linux]
    container:
      image: node:10.18-jessie
      options: --user 1000
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: active connections
        shell: bash
        run: |
          uname -a
          ps faux


  rubocop:
    name: Rubocop
    runs-on: [self-hosted, linux]
    env:
      ImageOS: "ubuntu20.04"
    steps:
      - name: Set runner-specific environment variables
        shell: bash
        run: |
          echo "ImageOS=ubuntu20" >> $GITHUB_ENV

      - name: "All env vars"
        run: env
      - name: "Sleeping"
        run: sleep 200
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
          bundler-cache: true
      - run: bundle exec rubocop


  test:
    name: Tests
    runs-on: [self-hosted, linux]

    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7]

    steps:
      - name: Set runner-specific environment variables
        shell: bash
        run: |
          echo "ImageOS=ubuntu20" >> $GITHUB_ENV

      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache
          key: ${{ runner.os }}-opt-hostedtoolcache
          restore-keys: |
            ${{ runner.os }}-opt-hostedtoolcache
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake test
## dummy change, iteration ==> 2
## dummy change, iteration ==> 3
## dummy change, iteration ==> 4
## dummy change, iteration ==> 5
## dummy change, iteration ==> 6
## dummy change, iteration ==> 7
## dummy change, iteration ==> 8
## dummy change, iteration ==> 9
## dummy change, iteration ==> 10
## dummy change, iteration ==> 11
## dummy change, iteration ==> 12
## dummy change, iteration ==> 13
## dummy change, iteration ==> 14
## dummy change, iteration ==> 15
## dummy change, iteration ==> 16
## dummy change, iteration ==> 17
## dummy change, iteration ==> 18
## dummy change, iteration ==> 19
